### ISSUE TITLE
Using different servers vs different groups

### ISSUE THREAD

**Issue by totalgee** [aiberlin/HyperDisCo#1]
Is the idea that people would use the (default) tcposcrouter server of `bgo.la`, or run their own server? If it's "okay" to use that server and port (which is set by default in the examples), then it would be good to expose the `groupName` and `groupPassword` arguments to `OSCRouterClient.new` to be set from `CodingDojo.new`, so we don't accidentally stomp on an existing live-coding session or workshop! Even if people use their own servers, it would still be useful to support different "rooms" (groups) at once.

Thanks, this project looks cool, I tried it out and it worked fine on first use, but would have liked to use a private group for experimenting.

**Comment by adcxyz** [comment]
Hi @totalgee, 
you are right, when making a CodingDojo directly, it is bad design to have groupName and password inaccessible, thus forcing the default values. This was convenient for our setup, but inconvenient for others. 
I would actually even prefer to change the order of args somewhat, see #3

**Comment by bgola** [comment]
Just to document it here, you can also run your own server, not sure if it is linked anywhere but the server code is here:

https://github.com/bgola/tcposcrouter

I will add some documentation to help setting up your own server. 
I have been pretty busy these days and didn't finish documenting :/

**Comment by adcxyz** [comment]
closed with f9b35fc0.

**Comment by totalgee** [comment]
Thanks @bgola, yes, we'll probably set up a server of our own. I'd already found the link to `tcposcrouter` repo from the HyperDisCo "documentation":

https://github.com/aiberlin/HyperDisCo/blob/0b2f0d6f28c93fda045d7bec37e332f387a037a1/HelpSource/OSCRouterClient.schelp#L7

Thanks for creating this, we look forward to playing around with it more... Besides this Quark's specific use case, having a general OSC message routing server is useful for live coding experimentation!
