### ISSUE TITLE
Butz and WinBounds classes are not defined

### ISSUE THREAD

**Issue by gilfuser** [aiberlin/HyperDisCo#11]
Hi guys. I'm finally starting to explore this wonderful Quark!

I'm following the 'examples' folder, but I can't make the GUI stuff because I don't have these classes Butz and WinBounds and I don't know where to find them.

If I Ctrl+D Butz, the Help System will show me `.butZone` in the ProxyChainGui but WinBounds won't lead me to anything.

Are they a Mac thing or it's just me missing something?

Any help will be much appreciated.

All the best,
Gil

**Comment by weego** [comment]
In adclib ? 

lG, 
Hannes

typed this on a "smart" keypad.

**Comment by gilfuser** [comment]
That's it!
I had an older version of adclib.
Now I remember I had it like so because in the newest version I can't have their GUIs if I use SCnvim, but this an issue for another repo.

thanks Hannes.

abraço,
Gil
