### ISSUE TITLE
OSCRouterClient: better argument order for matching

### ISSUE THREAD

**Issue by adcxyz** [aiberlin/HyperDisCo#3]
Design question:
For matching  and reusing existing instances, OSCRouterClient:match uses new args in the order of uniqueness so to speak: ```userName, groupName, serverAddr, serverport```.
If OSCRouterClient:new uses the same order for the first arguments, then one needs less jumping over default with keywords when re-accessing that oscrouter. 
```
// now: 
// arg serverAddr, userName, userPassword, onJoined,
		groupName, groupPassword, serverport;
~ex1 = OSCRouterClient("bgo.la", \ex1, \ex1pw, { }, \udkDojo, \dojopw);

// proposed order: 
// arg userName, groupName, serverAddr, userPassword, groupPassword, serverport, onJoined;
~ex1 = OSCRouterClient( \ex1,  \udkDojo, "bgo.la", \ex1pw, \dojopw, 55555, { });
```
With the new order of args, ```OSCRouterClient( \ex1,  \udkDojo, "bgo.la")```
is sufficient to find an OSCRouterClient again by those specs even if you have lots of oscrcs.
With only few oscrcs, ```OSCRouterClient( \ex1)``` or if needed, ```OSCRouterClient( \ex1, \udkDojo)``` is often sufficient as access pattern.
userPassword, groupPassword only need to be set on first use.
serverport will be left to default 99+% of the time, and
onJoined is not needed as an early arg, because ~oscr.join(func) does the same 
and is even clearer to reason about.

**Comment by bgola** [comment]
I agree with the change of arguments.

But I would like to have a way to instantiate multiple OSCRouterClients even if we the same username / group name, and maybe have a way to recover all the instances by matching a pattern.  Can be in another issue tho.

**Comment by adcxyz** [comment]
> I agree with the change of arguments.

cool, then I do it!

> But I would like to have a way to instantiate multiple OSCRouterClients even if we the same username / group name, 

You can do that, as long as _one_ of the four matchable items, user, group, server and port is different.  Making a second client with all four the same seems like a user error to me, no? 
So this is what I am trying to catch here - people running the same setup script again, and then we end up with zombie logins and unpredictable behavior etc...
Or do you have a use case where exactly that is needed?

> and maybe have a way to recover all the instances by matching a pattern. Can be in another issue tho. 

Currently all instances are in a Set, and findBy looks there, matching (if notNil) by  userName, groupName, server, and serverport. 
ATM, this findBy check happens automatically in .new.

**Comment by adcxyz** [comment]
done. 
ATTENTION: this update requires that users rewrite all calls to 
```OSCRouterClient/CodingDojo:new```  with these orders:
```
OSCRouterClient(<userName>, <groupName>, <serverAddr>, 
<userPassword>, <groupPassword>, <serverPort>, <onJoined>);
CodingDojo(<userName>, <groupName>, <serverAddr>, 
<userPassword>, <groupPassword>, <serverPort>);
```
