### ISSUE TITLE
add verbosity levels to OSCRouterClient, SyncText, CodingDojo

### ISSUE THREAD

**Issue by adcxyz** [aiberlin/HyperDisCo#7]
Given the complexity of network connections, info posting is really useful when things go wrong; 
when all is well, info posting can be reassuring, a bit like hearing a cat purring ;-), 
or (when all is known to be well), annoying, because it obscures other important posts.
So, rather than an on/off flag, I would propose a numerical verbosity level, 
where 0 means post nothing, 1 is post essentials, 2 is post "all is well" info too.

**Comment by bgola** [comment]
+1 for verbosity level

maybe a debug class could be useful

**Comment by adcxyz** [comment]
done with #12
